JuliaStats/Clustering.jl

doc/source/hclust.md, src/Clustering.jl, src/hclust.jl, src/types.jl, test/hclust.R, test/hclust.jl, test/runtests.jl
Hi, 
Following the suggestions from the METATDATA maintainers, I made a patch for Clustering to absorb the package Hclust (Hierarchical clustering along the lines of R's hclust() and cutree()), sice this is also does a form of clustering.  This keeps the number of packages down.  
I did not further integrate the code, it seems to be reasonably independent of the existing code in Clustering. 
---david
=> Inclusion of Hclust into Clustering.jl

src/dbscan.jl
This will no longer be true on 0.5 with new version of `NearestNeighbors`. Since this sits just behind a function barrier the type assert does not actually improves performance and can just be removed.
=> remove typeassert in KDTree

src/kmeans.jl, test/kmeans.jl
Adds keyword argument 'distance' to kmeans() and kmeans!() that defaults to Squared Euclidean but allows to specify another semi-metric to use for clustering. Additionally the user needs to provide a custom evaluate(dist, a, b) function for metrics that are not already available in Distances.jl.
=> Allow for arbitrary distance metrics for K-means clustering

src/mcl.jl, test/mcl.jl
Currently, if adjacency matrix values become small, during the inflation step, an inexact exception is thrown and algorithm is terminated. This PR removes this inexact exception, and substitutes it with a threshold pruning schema for column values which guarantees convergence of the algorithm.
This will fix #87 and recent CI test failures.
Ref: see 11.1.1 in "Graph clustering by flow simulation" by Stijn van Dongen.
=> Remove inexact exception in favor of values pruning in MCL

README.md
I can also remove Julia v0.4 link as it's quite outdated.
I'm about to tag v0.9.1 after this is merged: with #103 the tests are passing on v0.6 again.
=> Add PkgEvaluator link for Julia v0.6

src/fuzzycmeans.jl, test/fuzzycmeans.jl
The same change could be made in many other methods (looks like this package has lots of legacy code), but at least this is a step in the right direction.
=> Support AbstractMatrix in fuzzy_cmeans

src/kmeans.jl, src/seeding.jl, test/kmeans.jl, test/seeding.jl
See #136 and #129. 
I duplicated the existing tests to take effectively the same matrix but now wrapped in a `Transpose` object.
Benchmarks on 1.1 / libopenlibm for what it's worth
**Before**
```julia
julia> seed!(1234)
julia> X = randn(5000, 200);
julia> @btime kmeans($X, 2);
3.138 ms (35 allocations: 95.34 KiB)
julia> @btime kmeans(transpose($Xt), 2);          # ERRORS
julia> @btime kmeans(copy(transpose($Xt)), 2);
4.835 ms (37 allocations: 7.72 MiB)
```
**After**
```julia
julia> seed!(1234)
julia> X = randn(5000, 200);
julia> @btime kmeans($X, 2);
3.158 ms (35 allocations: 95.34 KiB)
julia> @btime kmeans(transpose($Xt), 2);     # WORKS
21.913 ms (54 allocations: 96.10 KiB)
julia> @btime kmeans(copy(transpose($Xt)), 2);
4.782 ms (37 allocations: 7.72 MiB)
```
So in short, the …
=> making kmeans take AbstractMatrix instead of Matrix

src/kmeans.jl, src/seeding.jl, src/utils.jl, test/kmeans.jl
With apologies for being back so soon... 
This applies the following changes
"**major**"
1. `x_int = rand(Int16, 10, 20); kmeans(x_int, 3)` ~~is now processed by converting `x_int`  into `Float64` (i.e. something sensible is returned instead of an error)~~ now works by making sure the centers are of an appropriately wide type see #140 for which a similar solution could be applied. Test added for that case.
2. types are now checked for consistency. Effectively at the entry points, the types for `X`, `centers` and `weights` can be whatever the user wants ~~but `_kmeans!` is effectively called on one single type which is `eltype(X)`. Since this happens after conversion, we're sure the result is a floating point number of some type `T` and all operations, distances and updates are done in …
=> refactoring of kmeans + type fixes

doc/source/conf.py
More recent Sphinx versions (1.4+) use imgmath instead of pngmath.
=> Fix doc build for Sphinx 1.4+

.travis.yml, README.md, REQUIRE
I suppose we don't need to support v0.7 anymore. Instead, I've added v1.1 to CI.
I also removed the package badges as they do not work for v1.0+.
=> Bump Julia to v1.0

README.md
Clustering.jl cannot and should not accommodate all existing clustering methods, but it's nice to inform the people about alternatives.
I'm not sure what should be the criteria for this list: should it be any packages tackling with the clustering problem or only high-quality actively maintained ones?
=> Add links to other clustering-related pkgs to README

doc/Project.toml, doc/make.jl, doc/source/index.md, doc/source/randindex.md, doc/source/silhouette.md, doc/source/varinfo.md, src/affprop.jl, src/dbscan.jl, src/fuzzycmeans.jl, src/hclust.jl, src/kmeans.jl, src/kmedoids.jl, src/mcl.jl, src/randindex.jl, src/seeding.jl, src/silhouette.jl, src/utils.jl, src/varinfo.jl, src/vmeasure.jl
Docstrings and Documenter .md files cleanups:
- address @nalimilan comments from #155
- consistently use `# Arguments` and `# References` section titles
- try to move paper references from .md into corresponding docstrings
- `func() -> output` format to document the return type in docstrings
- add the first (code) line to the docstrings of types
=> Cleanup docs

src/deprecate.jl, src/kmeans.jl, src/seeding.jl, test/kmeans.jl, test/seeding.jl
* more checks and tests for the params of seeding functions
* deprecate `copyseeds()`
* restore support for `init::Vector{Int}` and `init::SeedingAlgorithm` in `kmeans()` (#162)
* small cleanups
=> Seeding: checks, tests, cleanups

doc/source/algorithms.md, doc/source/fuzzycmeans.md, src/Clustering.jl, src/deprecate.jl, src/fuzzycmeans.jl, src/hclust.jl, src/kmeans.jl, src/utils.jl, test/fuzzycmeans.jl, test/kmeans.jl, test/kmedoids.jl
Some small counts/weights API improvements:
* add `wcounts(ClusteringResult)` (sum of the point weights)
* add `wcounts(FuzzyCMeansResult)` and `nclusters(FuzzyCMeansResult)`
* `FuzzyCMeansResult` is not a `ClusteringResult` (cannot have counts or assignments)
* rename `KMeansResult.cweights` into `KMeansResult.wcounts` for consistency (old property is still supported but deprecated)
=> wcounts() and tiny FuzzyCMeans API cleanups

Project.toml, REQUIRE, test/REQUIRE
With the [new package registration system](https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677/144), REQUIRE is out and Project.toml is in.
This is an annoying but necessary task, so I thought I'd just do it. I used [this script](https://github.com/JuliaLang/Pkg.jl/pull/1133), and added a version (`0.14.0`, since I figured this warranted a major version bump).
=> Switch from METADATA to registrator

Project.toml, src/deprecate.jl, src/kmedoids.jl
* Use `fieldnames()` to simplify property deprecations
* Add missing comments annotating deprecations with the package version it was introduced
* Move `KmedoidsResult` deprecations to `deprecate.jl`
=> Cleanup deprecations

Project.toml, src/deprecate.jl
The should call `fieldnames(typeof(x))` instead of `fieldnames(x)`
fixes #191
=> Fix propertynames() methods

Project.toml
- drop package versions for Julia-1.0-pre
- make it compatible with CompatHelper and conforming to automatic
merging requirements of JuliaRegistry
=> Update Project.toml [compat] section

src/affprop.jl, src/dbscan.jl, src/kmedoids.jl, test/affprop.jl, test/dbscan.jl, test/kmedoids.jl, test/test_helpers.jl
Affprop, DBScan and K-Mediods were dispatching on `DenseMatrix`.
This is a uncomfortable compromise as a great many matrix types, especially wrapper types, subtype `AbstractMatrix`.
(This makes sense the wrapper type doesn't know what it is wrapping).
I would be kind a surprised if any of the algorithms didn't work on structured or sparse matrixes.
Albeit with reduced performance and possibly large allocations.
But if they don't work for a particular type then that will throw its own error -- we don't need to  `MethodError` right at the start.
Examples of `AbstractMatrix` this should now support `Transpose`,`PermuteDims` and `SubArray`, `Symmetric` (rather makes sense for distances). And things from packages like `NamedDimsArray` and `StaticArray`.
I have added tests with the distance …
=> Make accept AbstractMatrix

test/vmeasure.jl
Since #211 we are using StableRNGs to make the tests more stable, but some methods (e.g. `kmeans()`) use random numbers in their implementation.
Try to fix vmeasure test by initializing Julia RNG and increasing the number of iterations.
=> tests: increase vmeasure test iterations to 200

test/counts.jl
The code is testing that `counts` with two empty input arrays produces an `ArgumentError`, which is failing because it actually produces a `MethodError` from a Base function deeper in the call stack. The method in question here is defined in StatsBase, not in this package, so it's unclear why this package is testing it to begin with.
=> Remove test for a method from StatsBase

doc/source/validate.md, src/Clustering.jl, src/confusion.jl, src/randindex.jl, test/confusion.jl, test/randindex.jl, test/runtests.jl
- added pair confusion matrix (CM) calculations
- fixed ARI calculation using CM
=> fixed ARI (fixes #225 & #226)

src/confusion.jl, src/randindex.jl, src/utils.jl, test/confusion.jl, test/randindex.jl
For very large clusterings the agreement/disagreement counts are very large, so we have to switch to float when multiplying them.
The PR improves the #227 and its test.
=> randindex(): fix int overflow

src/kmedoids.jl, test/kmedoids.jl
If medoids have duplicate coordinates, make
sure the medoid is assigned to itself, otherwise its cluster might be empty.
If the distance to itself is further than to another medoid, it is an issue with the distance matrix, and *ArgumentError* is raised.
My guess is that it should fix #231
=> kmedoids(): fix duplicate medoids case 

src/hclust.jl
This PR may increase performance in some cases and should pretty much never pose much of a regression. Perhaps more importantly, it drops a dependency on an undocumented internal method of Julia that may be removed in 1.10 because internals are not subject to SymVer.
In 1.9.0, Julia's `permute!` method got a bit more efficient. These benchmarks compare use of `permute!` to `permute!!`
```julia
julia> using BenchmarkTools, Random, Plots
julia> x = 2 .^ (3:26);
julia> GC.gc(); y!! = [(hmer_heights = rand(Int, n); o = randperm(n); @elapsed(Base.permute!!(hmer_heights, o))) for n in x];
julia> GC.gc(); y! = [(hmer_heights = rand(Int, n); o = randperm(n); @elapsed(permute!(hmer_heights, o))) for n in x];
julia> plot(x, y! ./ x, label="permute!"); plot!(x, y!! ./ x, label="permute!!", …
```
=> Stop using unexported Base.permute!!

Project.toml, src/kmeans.jl, src/seeding.jl, test/kmeans.jl
In 0.10.9 the signature of `pairwise()`/`colwise()` etc changed to have metric as the first argument (see JuliaStats/Distances.jl#239).
=> Update to Distances.jl 0.10.9

src/affprop.jl, test/affprop.jl
`affprob()` seems to fail in CI tests from time to time.
After looking at the debug info added by this PR, it looks like the failures are related to a numerical error accumulating in availability and response matrices.
It results in a very small negative `A[i,i] + R[i,i]`, which leads to the empty *exemplars*.
It looks like *sklearn* addresses that by adding small amount of noise: [*_affinity_propagation()*](https://github.com/scikit-learn/scikit-learn/blob/9aaed4987/sklearn/cluster/_affinity_propagation.py#L78).
=> Fix affprop() random CI failures

benchmark/benchmarks.jl, src/Clustering.jl, src/cluster_distances.jl, src/silhouette.jl, src/utils.jl, test/silhouette.jl
This PR implements a distributed implementation of silhouette score
https://arxiv.org/pdf/2303.14102.pdf
This implementation only supports Square Euclidean metric at the moment, but the extension to some (not all) other metrics is straightforward. See the paper.
This PR includes:
- Docs incl. usage example (see below)
- Implementation
- a bit of a refactor of the existing silhouette code (break it down into more functions to reuse in the new distributed implementation).
- Unit tests of the new implementation, including a comparison with the usual implementation.
Example including benchmarking
```
Julia> k=10; d=3; bs=100; n=10000;
Julia> pre = SilhouettesDistsPrecompute(k, d, Float32);
Julia> x = reshape(collect(Float32, 1:30000), 3, n); # direct computation is impractical on such a big …
```
=> Distributed silhouette

docs/source/fuzzycmeans.md, src/cluster_distances.jl, src/hclust.jl
Fix references to non-existent docstrings, convert docstrings of internal types to comments.
=> Fix documentation generation

docs/source/fuzzycmeans.md, src/fuzzycmeans.jl, src/utils.jl, test/fuzzycmeans.jl
* allow `dist_metric::SemiMetric`
* skip tolerance check for the 1st iteration (`prev_centers` are initialized to all zeroes, so it is not relevant to compare, and some metrics (e.g. `CorrDist`) are NaN in this case) 
* more informative error message if `display=` is specified incorrectly
* tweak `fuzzycmeans()` docs
=> fuzzycmeans() enhancements

README.md, docs/source/validate.md
=> Add ClusteringBenchmarks.jl reference

src/seeding.jl, src/utils.jl
Replace `updatemin!()` by `min.()` broadcasting; avoid loops
=> Cleanup kmeans() seeding

docs/source/validate.md
Third attempt at making this PR. I made a new repository and commit from a branch this time.
Corrections in links + changing `nclusters` to `№_clu`. There is a function `nclusters` already.
Something is deeply wrong with `Plots` when it compiles official docs for validate.md. Not only it puts titles on labels, it also does not display some labels at all. I  cannot reproduce it on two different machines, so currently I have no idea how to fix it.
EDIT. Looking more closely maybe it renders those labels, but they do not into the plot frames. Maybe we can try updating `Plots` version in docs?
=> Small corrections in docs validate.md
