JuliaStats/Clustering.jl

- src/kmeans.jl
This was a major bottleneck for clustering in 2d. See https://groups.google.com/d/msg/julia-users/G4ktbB-n7ug/8iF2WcaeQb8J
> Avoid view construction in update_centers!

- doc/source/randindex.rst
- doc/source/validate.rst
- src/Clustering.jl
- src/randindex.jl
- test/randindex.jl
- test/runtests.jl
I have taken and refactored a bit implementation for issue https://github.com/JuliaStats/Clustering.jl/issues/48 from the [MATLAB](http://www.mathworks.com/matlabcentral/fileexchange/13916--simple--tool-for-estimating-the-number-of-clusters/content/valid_RandIndex.m) central
> Implementation for issue #48

- .travis.yml
- README.md
- REQUIRE
- src/Clustering.jl
- src/hclust.jl
- src/randindex.jl
- test/affprop.jl
- test/kmeans.jl
The biggest changes here are removing support for Julia 0.3 and removing the dependency on ArrayViews. Besides that, I bumped the required package versions, removed trailing whitespace, and replaced tabs with 4 spaces for consistency.
Fixes #66.
> Updates for 0.5

- src/dbscan.jl
> Make DBSCAN minimum points inequalities consistently non-strict

- src/Clustering.jl
- src/mcl.jl
- test/mcl.jl
- test/runtests.jl
Adds MCL (Markov Cluster Algorithm) for weighted graphs (http://micans.org/mcl/).
> Add MCL (Markov Clustering) + tests

- REQUIRE
Addresses https://github.com/JuliaStats/Clustering.jl/pull/82#discussion_r112545906. Will update the 0.8.0 tag once this is merged.
cc @tkelman
> Drop the Compat requirement down to 0.17

- src/kmeans.jl
A minor fix for `kmeans` for the issue stated in #91
> Fix for kmeans

- src/hclust.jl
- test/hclust.jl
Just some spacing, `≤` rather than `<=`, and some double-for-loop rewrites in my own code.
> Cosmetic changes in hclust.jl

- src/dbscan.jl
- test/dbscan.jl
This PR fixes type inconsistency in dbscan (fixes #84)
> Fix type inconsistency in dbscan call

- README.md
Added for reference a list of algorithms to README.md
> add list of algorithms to README.md

- doc/source/hclust.rst
> hclust() docs: small style fixes

- .travis.yml
- REQUIRE
- src/Clustering.jl
- src/affprop.jl
- src/dbscan.jl
- src/deprecate.jl
- src/fuzzycmeans.jl
- src/hclust.jl
- src/kmeans.jl
- src/kmedoids.jl
- src/mcl.jl
- src/randindex.jl
- src/seeding.jl
- src/silhouette.jl
- src/types.jl
- src/utils.jl
- test/REQUIRE
- test/affprop.jl
- test/dbscan.jl
- test/fuzzycmeans.jl
- test/hclust.jl
- test/kmeans.jl
- test/kmedoids.jl
- test/mcl.jl
- test/randindex.jl
- test/runtests.jl
- test/seeding.jl
- test/silhouette.jl
- test/varinfo.jl
This should trigger FemtoCleaner. Closes #117.
> Raise minimum Julia version to 0.7

- src/silhouette.jl
- test/silhouette.jl
> test added

- LICENSE.md
- src/silhouette.jl
- test/silhouette.jl
* allow `AbstractVector`/`AbstractMatrix`
* Make `counts` param optional
* `silhouettes()` eltype depends on `dist` eltype
* more param checks
* add docstring
> Misc. silhouettes() improvements

- REQUIRE
- benchmark/benchmarks.jl
- src/fuzzycmeans.jl
- src/kmeans.jl
- src/seeding.jl
- test/affprop.jl
- test/dbscan.jl
- test/kmeans.jl
- test/kmedoids.jl
- test/seeding.jl
Fixes #146 . Some tests fail, but it is already the case on master.
> Add 'dims=2' to all 'pairwise' and 'pairwise!' calls

- doc/source/algorithms.rst
- doc/source/fuzzycmeans.rst
- src/fuzzycmeans.jl
I noticed a very minor bug in the iteration display of fuzzy c-means. I fixed that and added a preliminary version of documentation for the function (I wrote it pretty quickly so let me know if there are any issues)
> FuzzyCMeans: fix logging bug and add initial documentation

- src/kmeans.jl
- test/kmeans.jl
- test/kmedoids.jl
(possibly) closes #183 
It looks like kmedoids already supports k=1 and k=n, at least it doesn't throw an error if so.
So this PR only interacts with kmeans.
> kmeans corner cases for k=1 and k=n

- doc/source/kmedoids.md
- src/kmedoids.jl
- test/kmedoids.jl
closes #98 
I figured it made sense to provide a finished version of #98, since it was seen to have been a good idea at the time.
However, it'll quite likely break some workflows. Is it still desired?
> rename kmedoids acost to cost re #98

- doc/source/kmedoids.md
- src/kmedoids.jl
Essentially, #178 + references added to the k-medoids docs.
> Correct & expand k-medoids implementation note

- Project.toml
> Bump Distances.jl

- src/silhouette.jl
- test/silhouette.jl
> silhouette(): fix empty clusters case

- .github/workflows/CompatHelper.yml
- .github/workflows/TagBot.yml
- .github/workflows/ci.yml
- Project.toml
- doc/Project.toml
- doc/source/hclust.md
- doc/source/kmeans.md
Use recent versions of GH actions, add descriptions of run scripts.
> Update CI scripts
